x-sensor-env: &sensor-env
  KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
  TOPIC_TEMPERATURA: temperatura
  TOPIC_VIBRACAO: vibracao
  TOPIC_ENERGIA: energia
  SENSOR_INTERVAL_MS: 1000
  ANOMALY_PROBABILITY: 0.05

services:
  kafka-1:
    image: apache/kafka:3.8.0

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_NUM_PARTITIONS: 6
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

    volumes:
      - kafka-data-1:/var/lib/kafka/data

    networks:
      - int-network


  kafka-2:
    image: apache/kafka:3.8.0

    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_NUM_PARTITIONS: 6
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

    volumes:
      - kafka-data-2:/var/lib/kafka/data

    networks:
      - int-network


  kafka-3:
    image: apache/kafka:3.8.0

    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

      KAFKA_NUM_PARTITIONS: 6
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2

    volumes:
      - kafka-data-3:/var/lib/kafka/data

    networks:
      - int-network

  producer-producao:
    build: ./producer-service

    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

    networks:
      - int-network
      - ext-network

    environment:
      <<: *sensor-env
      SENSOR_SETOR: producao
      TEMP_MIN: 20
      TEMP_MAX: 70
      VIB_MIN: 0
      VIB_MAX: 5
      ENERGIA_MIN: 5
      ENERGIA_MAX: 50

  producer-refrigeracao:
    build: ./producer-service

    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

    networks:
      - int-network
      - ext-network

    environment:
      <<: *sensor-env
      SENSOR_SETOR: refrigeracao
      TEMP_MIN: 5
      TEMP_MAX: 15
      VIB_MIN: 0
      VIB_MAX: 5
      ENERGIA_MIN: 5
      ENERGIA_MAX: 100
    
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    
  
  producer-empacotamento:
    build: ./producer-service

    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

    networks:
      - int-network
      - ext-network

    environment:
      <<: *sensor-env
      SENSOR_SETOR: empacotamento
      TEMP_MIN: 20
      TEMP_MAX: 30
      VIB_MIN: 0
      VIB_MAX: 5
      ENERGIA_MIN: 5
      ENERGIA_MAX: 10
    
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
  
  consumer-service:
    build: ./consumer-service

    ports:
      - "8081:8080"

    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

    networks:
      - ext-network
      - int-network

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092


volumes:
  kafka-data-1:
  kafka-data-2:
  kafka-data-3:

networks:
  ext-network:
    driver: bridge

  int-network:
    driver: bridge
    internal: true